### ISSUE TITLE
Player chat mute

### ISSUE THREAD

**Issue by makeevrserg** [whereareiam/Socialismus#47]
## **Background**
Some people can spam messages in chat and ignore moderator warns. The Socialimus have higher priority than EssentialsX, for example, so EssentialsX's `/mute` command doesn't affect Socialimus. The players still can write messages

Moreover, as chat-based plugin, Socialimus should have this feature to use it with Socialimus-only. 

## **Description**
After writing comand `/socmute <TIME> <PLAYER>` (just an example name for command) the player should be muted for 10 minutes.
- <TIME> - the time for mute, described below
- <PLAYER> - the name of player to mute
### The avaliable timings:
- `m` - Minutes
- `h` - Hours
- `d` - Days

### Algorithm detail
There's no need to save this data inside SQLite database or in any file format. In-memory HashMap<UUID, Boolean> will be enough for this feature. Yes, server can've restarded during player mute, but I thunk there's no need to create overhead in codebase to handle this

**Comment by whereareiam** [comment]
Hi, thanks for your suggestion, in my opinion the moderation stuff belongs to another plugin, so there wouldn't be any mute functionality. 

And to address your problem, this can be easily fixed in the 2.0 version of the plugin (which is currently in beta), you can set the priority of the events there. By the way, does this problem also occur when using LibertyBans or LiteBans?

**Comment by makeevrserg** [comment]
> By the way, does this problem also occur when using LibertyBans or LiteBans

I don't see this problem with LibertyBans.

> the moderation stuff belongs to another plugin

Well, you are probably right. Maybe the moderation chat should be managed by moderation plugin, not chat-based plugin.

> you can set the priority of the events there

That's great. Thanks for your response!
